package Forms_Alfa;

import Extras.CORBA_Conn;
import Extras.Data;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isay
 */
public class FNormal extends CORBA_Conn {
    private DefaultTableModel modeloP, modeloT;
    private Data me;
    public FTablesNorm ftN;
    public Profile p;
    public NewPwd pwd;
    public NewT nt;    

    /** Creates new form FNormal */
    public FNormal() {
        initComponents();
        setTitulosTablas();
    }
    
    private void setTitulosTablas(){
        String[] titulosP = {"ID", "Nombre del Proyecto", "Lider del Proyecto", "Descripción", "Fecha de Inicio", "Fecha de Termino"};
        modeloP = new DefaultTableModel(null, titulosP);
        String[] titulos = {"ID", "Nombre de la Tarea", "Proyecto", "Descripción", "Fecha de Inicio", 
            "Fecha de Termino", "Prioridad", "Proceso"};
        modeloT = new DefaultTableModel(null, titulos);
    }
    
    private void removeRows(DefaultTableModel modelo){
        int count = modelo.getRowCount() - 1;
        for(int i = count; i >= 0; i--)
                modelo.removeRow(i);
    }
    
    public void loadTablaProy(javax.swing.JTable tabla, DefaultTableModel modelo, javax.swing.JComboBox caja){
        String[][] registros = exRef.ObtenerMisProyectos(me.Id(), false);
        String[] registro = new String[6];
        removeRows(modelo);
        int contador = 0;
        caja.removeAllItems();        
        while(true){
            try{
                registro[0] = registros[0][contador];                
                registro[1] = registros[2][contador];
                registro[2] = registros[1][contador];
                registro[3] = registros[3][contador];
                registro[4] = registros[4][contador];
                registro[5] = registros[5][contador];
                caja.addItem(new Data(Integer.parseInt(registro[0]), registro[1]));
                contador++;
                modelo.addRow(registro);
            }catch(Exception e){ break; }            
        }             
        tabla.setModel(modelo);        
    }
    
    public void loadTablaTarea(javax.swing.JTable tabla, DefaultTableModel modelo, javax.swing.JComboBox caja){
        String[][] registros = exRef.ObtenerMisTareas(me.Id(), false);        
        String[] registro = new String[8];
        removeRows(modelo);
        int contador = 0;
        while(true){            
            try{
                registro[0] = registros[0][contador];
                registro[1] = registros[2][contador];
                registro[2] = registros[1][contador];
                registro[3] = registros[3][contador];
                registro[4] = registros[4][contador];
                registro[5] = registros[5][contador];
                registro[6] = registros[6][contador];
                registro[7] = registros[7][contador];
                contador++;                
                if(caja.getSelectedItem().toString().equals(registro[2]))
                    modelo.addRow(registro);
            }catch(Exception e){ break; }            
        }       
        tabla.setModel(modelo);
    }        
    
    public void Refresh(){
        loadTablaProy(tblProy, modeloP, cboOrganizarT);
        loadTablaTarea(tblTareas, modeloT, cboOrganizarT);
    }
    
    public void modify(javax.swing.JTable tabla){
        try{
            int fila = tabla.getSelectedRow();
            if(fila == -1) 
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una tarea", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(nt == null){
                    nt = new NewT();
                    nt.setDatos(new Data(Integer.parseInt(tabla.getValueAt(fila, 0).toString()), 
                            tabla.getValueAt(fila, 1).toString()), tabla.getValueAt(fila, 2).toString(),
                            tabla.getValueAt(fila, 3).toString(), 
                            tabla.getValueAt(fila, 4).toString(), tabla.getValueAt(fila, 5).toString(), 
                            tabla.getValueAt(fila, 6).toString(), tabla.getValueAt(fila, 7).toString(), 
                            false);
                }
                nt.setFNormal(this);
                nt.setVisible(true);
            }
        }catch(Exception e){            
            JOptionPane.showMessageDialog(null, e, "Error al seleccionar", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void setData(Data u){
        me = u;
        lblName.setText(me.Name());
        Refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        pictureBox1 = new PictureBox.PictureBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProy = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboOrganizarT = new javax.swing.JComboBox();
        btnOrganizarT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProject = new javax.swing.JMenu();
        mnCerrarSesion = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();
        mnAyuda = new javax.swing.JMenu();
        mnAcerca = new javax.swing.JMenuItem();
        mnAyuda1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvenido(a)");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblName.setText("Nombre");

        btnPerfil.setText("Editar Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        pictureBox1.setArchivo("E:\\Isay\\Documentos\\Universidad de Colima\\5 semestre\\Programación Distribuida\\Programas\\Jupiter(alfa)\\src\\no user.jpg");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mis Proyectos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        tblProy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProy);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Abrir en otra ventana");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mis Tareas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTareas);

        jLabel1.setText("Organizar Por:");

        btnOrganizarT.setText("Organizar");
        btnOrganizarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizarTActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Abrir en otra ventana");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnModificar.setText("Modificar Progreso de la Tarea Seleccionada");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboOrganizarT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrganizarT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboOrganizarT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrganizarT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnModificar)))
        );

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Cambiar Contraseña");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Cerrar Sesión");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        mnuProject.setText("uProject");

        mnCerrarSesion.setText("Cerrar Sesión");
        mnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarSesionActionPerformed(evt);
            }
        });
        mnuProject.add(mnCerrarSesion);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnuProject.add(mnSalir);

        jMenuBar1.add(mnuProject);

        mnAyuda.setText("Ayuda");

        mnAcerca.setText("Acerca de...");
        mnAyuda.add(mnAcerca);

        mnAyuda1.setText("Ayuda");
        mnAyuda.add(mnAyuda1);

        jMenuBar1.add(mnAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(btnPerfil)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnOrganizarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizarTActionPerformed
        loadTablaTarea(tblTareas, modeloT, cboOrganizarT);
    }//GEN-LAST:event_btnOrganizarTActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        if(p == null){
            p = new Profile();
            p.setData(me, true);
            p.setVisiblePriv(false); 
            p.setFNormal(this);
        }
        p.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(pwd == null){
            pwd = new NewPwd();
            pwd.setMe(me);
            pwd.setFNormal(this);
        }
        pwd.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(ftN == null) ftN = new FTablesNorm();
        ftN.setData(me, this);
        ftN.setIndex(0);
        ftN.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(ftN == null) ftN = new FTablesNorm();
        ftN.setData(me, this);
        ftN.setIndex(1);
        ftN.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modify(tblTareas);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarSesionActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FNormal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnOrganizarT;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JComboBox cboOrganizarT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenuItem mnAcerca;
    private javax.swing.JMenu mnAyuda;
    private javax.swing.JMenuItem mnAyuda1;
    private javax.swing.JMenuItem mnCerrarSesion;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenu mnuProject;
    private PictureBox.PictureBox pictureBox1;
    private javax.swing.JTable tblProy;
    private javax.swing.JTable tblTareas;
    // End of variables declaration//GEN-END:variables
}
