package Forms_Alfa;

import Extras.CORBA_Conn;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isay
 */
public class Trash extends CORBA_Conn {
    private DefaultTableModel modelo;
    private FAdmin fa;

    /** Creates new form Trash */
    public Trash() {
        initComponents();
        centrarVentana();
        pgbProgress.setVisible(false);
        loadTablaProy("");
        loadTablaTarea("");
        loadTablaUser("");
    }
    
    public void setFAdmin(FAdmin fa){this.fa = fa;}
    
    void loadTablaProy(String busqueda){
        String[] titulos = {"ID", "Nombre del Proyecto", "Lider del Proyecto", "Descripción", "Fecha de Inicio", "Fecha de Termino"};
        modelo = new DefaultTableModel(null, titulos);
        String[][] registros = exRef.Obtener(busqueda, (byte)0, (byte)1);
        String[] registro = new String[6];
        int contador = 0;        
        while(true){
            try{
                registro[0] = registros[0][contador];                
                registro[1] = registros[2][contador];
                registro[2] = registros[1][contador];
                registro[3] = registros[3][contador];
                registro[4] = registros[4][contador];
                registro[5] = registros[5][contador];                
                contador++;
                modelo.addRow(registro);
            }catch(Exception e){ break; }            
        }        
        tblProy.setModel(modelo);
    }
    
    void loadTablaTarea(String busqueda){
        String[] titulos = {"ID", "Nombre de la Tarea", "Proyecto", "Descripción", "Fecha de Inicio", 
            "Fecha de Termino", "Prioridad", "Progreso"};
        modelo = new DefaultTableModel(null, titulos);
        String[][] registros = exRef.Obtener(busqueda, (byte)0, (byte)2);
        String[] registro = new String[8];
        int contador = 0;
        while(true){
            try{
                registro[0] = registros[0][contador];                
                registro[1] = registros[2][contador];
                registro[2] = registros[1][contador];
                registro[3] = registros[3][contador];
                registro[4] = registros[4][contador];
                registro[5] = registros[5][contador];
                registro[6] = registros[6][contador];
                registro[7] = registros[7][contador];
                contador++;
                modelo.addRow(registro);
            }catch(Exception e){ break; }            
        }        
        tblTareas.setModel(modelo);
    }
    
    void loadTablaUser(String busqueda){
        String[] titulos = {"ID", "Usuario", "Privilegio", "Nombre", "Email", "Género", "Fecha de Nacimiento"};
        modelo = new DefaultTableModel(null, titulos);        
        String[][] registros = exRef.Obtener(busqueda, (byte)0, (byte)3);
        String[] registro = new String[7];
        int contador = 0;
        while(true){
            try{
                registro[0] = registros[0][contador];
                registro[1] = registros[1][contador];
                registro[2] = registros[3][contador];
                registro[3] = registros[4][contador];
                registro[4] = registros[5][contador];
                registro[5] = registros[6][contador];
                registro[6] = registros[7][contador];
                contador++;
                modelo.addRow(registro);
            }catch(Exception e){ break; }            
        }
        tblUsers.setModel(modelo);
    }
    
    void RestaurarTodos(javax.swing.JTable tabla, byte tablaBD){
        pgbProgress.setMaximum(tabla.getRowCount());
        while(true){
            try{
                modelo = (DefaultTableModel)tabla.getModel();
                fa.exRef.Restaurar(Integer.parseInt(tabla.getValueAt(0, 0).toString()), tablaBD);
                tabla.setModel(modelo);
                pgbProgress.setValue(pgbProgress.getValue() + 1);
            }catch(Exception e){
                pgbProgress.setMaximum(10);
                fa.Refresh();
                pgbProgress.setValue(5);
                if(fa.ftA != null)fa.ftA.Refresh();
                pgbProgress.setValue(0);
                break;
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbp1 = new javax.swing.JTabbedPane();
        pProyectos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarP = new javax.swing.JTextField();
        btnBuscarP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProy = new javax.swing.JTable();
        btnRestaurarP = new javax.swing.JButton();
        btnRestaurarTodosP = new javax.swing.JButton();
        btnEliminarTodosP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        pTareas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarT = new javax.swing.JTextField();
        btnBuscarT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        btnRestaurarT = new javax.swing.JButton();
        btnRestaurarTodosT = new javax.swing.JButton();
        btnEliminarTodosT = new javax.swing.JButton();
        btnEliminarT = new javax.swing.JButton();
        pUsuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarU = new javax.swing.JTextField();
        btnBuscarU = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnRestaurarU = new javax.swing.JButton();
        btnRestaurarTodosU = new javax.swing.JButton();
        btnEliminarTodosU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pgbProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Papelera");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbp1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tbp1.setFont(new java.awt.Font("Tahoma", 1, 14));

        jLabel1.setText("Buscar Proyectos:");

        btnBuscarP.setText("Buscar");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        tblProy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProy);

        btnRestaurarP.setText("Restaurar Seleccionado");
        btnRestaurarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarPActionPerformed(evt);
            }
        });

        btnRestaurarTodosP.setText("Restaurar Todos");
        btnRestaurarTodosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarTodosPActionPerformed(evt);
            }
        });

        btnEliminarTodosP.setText("Eliminar Todos");
        btnEliminarTodosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosPActionPerformed(evt);
            }
        });

        btnEliminarP.setText("Eliminar Seleccionado");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProyectosLayout = new javax.swing.GroupLayout(pProyectos);
        pProyectos.setLayout(pProyectosLayout);
        pProyectosLayout.setHorizontalGroup(
            pProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(pProyectosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarP))
                    .addGroup(pProyectosLayout.createSequentialGroup()
                        .addComponent(btnRestaurarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurarTodosP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(btnEliminarP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodosP)))
                .addContainerGap())
        );
        pProyectosLayout.setVerticalGroup(
            pProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurarTodosP)
                    .addComponent(btnRestaurarP)
                    .addComponent(btnEliminarTodosP)
                    .addComponent(btnEliminarP))
                .addContainerGap())
        );

        tbp1.addTab("Papelera de Proyectos", pProyectos);

        jLabel2.setText("Buscar Tareas:");

        btnBuscarT.setText("Buscar");
        btnBuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTActionPerformed(evt);
            }
        });

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTareas);

        btnRestaurarT.setText("Restaurar Seleccionado");
        btnRestaurarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarTActionPerformed(evt);
            }
        });

        btnRestaurarTodosT.setText("Restaurar Todos");
        btnRestaurarTodosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarTodosTActionPerformed(evt);
            }
        });

        btnEliminarTodosT.setText("Eliminar Todos");
        btnEliminarTodosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosTActionPerformed(evt);
            }
        });

        btnEliminarT.setText("Eliminar Seleccionado");
        btnEliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTareasLayout = new javax.swing.GroupLayout(pTareas);
        pTareas.setLayout(pTareasLayout);
        pTareasLayout.setHorizontalGroup(
            pTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(pTareasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarT))
                    .addGroup(pTareasLayout.createSequentialGroup()
                        .addComponent(btnRestaurarT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurarTodosT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(btnEliminarT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodosT)))
                .addContainerGap())
        );
        pTareasLayout.setVerticalGroup(
            pTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurarTodosT)
                    .addComponent(btnRestaurarT)
                    .addComponent(btnEliminarTodosT)
                    .addComponent(btnEliminarT))
                .addContainerGap())
        );

        tbp1.addTab("Papelera de Tareas", pTareas);

        jLabel3.setText("Buscar Usuarios:");

        btnBuscarU.setText("Buscar");
        btnBuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblUsers);

        btnRestaurarU.setText("Restaurar Seleccionado");
        btnRestaurarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarUActionPerformed(evt);
            }
        });

        btnRestaurarTodosU.setText("Restaurar Todos");
        btnRestaurarTodosU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarTodosUActionPerformed(evt);
            }
        });

        btnEliminarTodosU.setText("Eliminar Todos");
        btnEliminarTodosU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosUActionPerformed(evt);
            }
        });

        btnEliminarU.setText("Eliminar Seleccionado");
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUsuariosLayout = new javax.swing.GroupLayout(pUsuarios);
        pUsuarios.setLayout(pUsuariosLayout);
        pUsuariosLayout.setHorizontalGroup(
            pUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(pUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarU))
                    .addGroup(pUsuariosLayout.createSequentialGroup()
                        .addComponent(btnRestaurarU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurarTodosU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(btnEliminarU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodosU)))
                .addContainerGap())
        );
        pUsuariosLayout.setVerticalGroup(
            pUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestaurarTodosU)
                    .addComponent(btnRestaurarU)
                    .addComponent(btnEliminarTodosU)
                    .addComponent(btnEliminarU))
                .addContainerGap())
        );

        tbp1.addTab("Papelera de Usuarios", pUsuarios);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbp1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        fa.tr = null;
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        loadTablaProy(txtBuscarP.getText());
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void btnBuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTActionPerformed
        loadTablaTarea(txtBuscarT.getText());
    }//GEN-LAST:event_btnBuscarTActionPerformed

    private void btnBuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUActionPerformed
        loadTablaUser(txtBuscarU.getText());
    }//GEN-LAST:event_btnBuscarUActionPerformed

    private void btnRestaurarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarPActionPerformed
        try{
            int fila = tblProy.getSelectedRow();
            if(fila == -1) 
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(exRef.Restaurar(Integer.parseInt(tblProy.getValueAt(fila, 0).toString()), (byte)1)){
                    loadTablaProy("");
                    fa.Refresh();
                    if(fa.ftA != null) fa.ftA.Refresh();
                    JOptionPane.showMessageDialog(null, "El elemento se ha restaudaro satisfactoriamente.", "Restaura Proyecto", JOptionPane.PLAIN_MESSAGE);
                }else JOptionPane.showMessageDialog(null, "Ocurrió un error al tratar de restaurar el elemento seleccionado.", "Restaura Proyecto", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){            
            JOptionPane.showMessageDialog(null, e, "Error al seleccionar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarPActionPerformed

    private void btnRestaurarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarTActionPerformed
        try{
            int fila = tblTareas.getSelectedRow();
            if(fila == -1) 
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(exRef.Restaurar(Integer.parseInt(tblTareas.getValueAt(fila, 0).toString()), (byte)2)){
                    loadTablaTarea("");
                    fa.Refresh();
                    if(fa.ftA != null) fa.ftA.Refresh();
                    JOptionPane.showMessageDialog(null, "El elemento se ha restaudaro satisfactoriamente.", "Restaura Tarea", JOptionPane.PLAIN_MESSAGE);
                }else JOptionPane.showMessageDialog(null, "Ocurrió un error al tratar de restaurar el elemento seleccionado.", "Restaura Tarea", JOptionPane.ERROR_MESSAGE);
                
            }
        }catch(Exception e){            
            JOptionPane.showMessageDialog(null, e, "Error al seleccionar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarTActionPerformed

    private void btnRestaurarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarUActionPerformed
        try{
            int fila = tblUsers.getSelectedRow();
            if(fila == -1) 
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(exRef.Restaurar(Integer.parseInt(tblUsers.getValueAt(fila, 0).toString()), (byte)3)){
                    loadTablaUser("");
                    fa.Refresh();
                    if(fa.ftA != null) fa.ftA.Refresh();
                    JOptionPane.showMessageDialog(null, "El elemento se ha restaudaro satisfactoriamente.", "Restaura Usuario", JOptionPane.PLAIN_MESSAGE);
                }else JOptionPane.showMessageDialog(null, "Ocurrió un error al tratar de restaurar el elemento seleccionado.", "Restaura Usuario", JOptionPane.ERROR_MESSAGE);
                
            }
        }catch(Exception e){            
            JOptionPane.showMessageDialog(null, e, "Error al seleccionar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarUActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fa.tr = null;
    }//GEN-LAST:event_formWindowClosing

    private void btnRestaurarTodosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarTodosPActionPerformed
        RestaurarTodos(tblProy, (byte)1);        
    }//GEN-LAST:event_btnRestaurarTodosPActionPerformed
    
    private void btnRestaurarTodosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarTodosTActionPerformed
        RestaurarTodos(tblTareas, (byte)2);        
    }//GEN-LAST:event_btnRestaurarTodosTActionPerformed

    private void btnRestaurarTodosUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarTodosUActionPerformed
        RestaurarTodos(tblUsers, (byte)3);        
    }//GEN-LAST:event_btnRestaurarTodosUActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        fa.deleteProject(tblProy);
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnEliminarTodosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosPActionPerformed
        if(fa.ftA != null) fa.ftA.trashdeleteProyectTask(tblProy, modelo, true, (byte)1);
        else{
            fa.ftA = new FTablesAdmin();
            fa.ftA.trashdeleteProyectTask(tblProy, modelo, true, (byte)1);
            fa.ftA = null;
        }
    }//GEN-LAST:event_btnEliminarTodosPActionPerformed

    private void btnEliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTActionPerformed
        fa.deleteTask(tblTareas);
    }//GEN-LAST:event_btnEliminarTActionPerformed

    private void btnEliminarTodosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosTActionPerformed
        if(fa.ftA != null) fa.ftA.trashdeleteProyectTask(tblTareas, modelo, true, (byte)2);
        else{
            fa.ftA = new FTablesAdmin();
            fa.ftA.trashdeleteProyectTask(tblTareas, modelo, true, (byte)2);
            fa.ftA = null;
        }
    }//GEN-LAST:event_btnEliminarTodosTActionPerformed

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        fa.deleteUser(tblUsers);
    }//GEN-LAST:event_btnEliminarUActionPerformed

    private void btnEliminarTodosUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosUActionPerformed
        if(fa.ftA != null) fa.ftA.trashdeleteUser(tblUsers, modelo, true);
        else{
            fa.ftA = new FTablesAdmin();
            fa.ftA.trashdeleteUser(tblUsers, modelo, true);
            fa.ftA = null;
        }
    }//GEN-LAST:event_btnEliminarTodosUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Trash().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnBuscarT;
    private javax.swing.JButton btnBuscarU;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnEliminarT;
    private javax.swing.JButton btnEliminarTodosP;
    private javax.swing.JButton btnEliminarTodosT;
    private javax.swing.JButton btnEliminarTodosU;
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JButton btnRestaurarP;
    private javax.swing.JButton btnRestaurarT;
    private javax.swing.JButton btnRestaurarTodosP;
    private javax.swing.JButton btnRestaurarTodosT;
    private javax.swing.JButton btnRestaurarTodosU;
    private javax.swing.JButton btnRestaurarU;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pProyectos;
    private javax.swing.JPanel pTareas;
    private javax.swing.JPanel pUsuarios;
    private javax.swing.JProgressBar pgbProgress;
    private javax.swing.JTable tblProy;
    private javax.swing.JTable tblTareas;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTabbedPane tbp1;
    private javax.swing.JTextField txtBuscarP;
    private javax.swing.JTextField txtBuscarT;
    private javax.swing.JTextField txtBuscarU;
    // End of variables declaration//GEN-END:variables
}
