package ExApp;


/**
* ExApp/Ex.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ex.idl
* lunes 7 de noviembre de 2011 20H31' CST
*/

public interface Ex extends ExOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ex
