package ExApp;


/**
* ExApp/matrizHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ex.idl
* lunes 7 de noviembre de 2011 20H31' CST
*/

public final class matrizHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[][] = null;

  public matrizHolder ()
  {
  }

  public matrizHolder (String[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExApp.matrizHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExApp.matrizHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExApp.matrizHelper.type ();
  }

}
