package ExApp;


/**
* ExApp/vectorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ex.idl
* lunes 7 de noviembre de 2011 20H31' CST
*/

public final class vectorHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public vectorHolder ()
  {
  }

  public vectorHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExApp.vectorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExApp.vectorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExApp.vectorHelper.type ();
  }

}
